"""
学术报告生成模块（模块5 / Module 5）

按 报告格式设计.md（权威规范）渲染固定四段式学术报告（MD / PDF）：
  标题 + 时间  →  一、报告速览  →  二、分类论文展示（热点聚类）  →  三、研究趋势

实现要点（对照权威规范，已修正计划代码的差异）：
  1. 双语：默认按 intent.language 驱动；默认值 bilingual（骨架全双语，正文按原语种）。
  2. 标题：bilingual 时双语两行（§7）。
  3. 时间标签：bilingual 时双语（§3/§7）。
  4. 速览：按热点分组、逐篇概述每篇核心内容，覆盖全部论文（不丢论文）。
  5. 研究趋势：趋势/缺口均从本次收录论文派生，避免空泛套话（§6）。
  6. 单篇块：四要素摘录（解决的问题/现有方案/新方案/效果及局限性），由
     analyzer.StructuredExtractor 从摘要中抽取语段；四要素全空时回退完整 Abstract。
  7. Option B：热点介绍/整体分析/奠基论文**委托** paper_filter 与 paper_analyzer，不再自带。

依赖：paper_filter.PaperFilter、paper_analyzer.PaperAnalyzer、utils、reportlab（PDF）。
"""

from __future__ import annotations

import io
import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

from utils import Paper, SearchIntent, format_apa_citation

# reportlab 懒加载（纯 Python wheel，无系统依赖；中文走 reportlab 内置 CID 字体
# STSong-Light，无需 .ttf 文件、无需系统字体）。未安装时 _HAS_REPORTLAB=False，
# _convert_to_pdf 抛 RuntimeError，由 generate_both 捕获后回退仅输出 MD。
PDF_FONT_NAME = "STSong-Light"
_HAS_REPORTLAB = True
try:  # pragma: no cover - 仅在 reportlab 未安装时走此分支
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, HRFlowable, Table, TableStyle,
        CondPageBreak,
    )
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.cidfonts import UnicodeCIDFont
except ImportError:  # pragma: no cover
    _HAS_REPORTLAB = False

_PDF_FONTS_READY = False


def _ensure_pdf_fonts() -> None:
    """注册 CID 字体 STSong-Light（幂等；重复注册无害）。"""
    global _PDF_FONTS_READY
    if _PDF_FONTS_READY or not _HAS_REPORTLAB:
        return
    try:
        pdfmetrics.registerFont(UnicodeCIDFont(PDF_FONT_NAME))
    except Exception:
        pass  # 已注册 / 不可用：交由渲染阶段处理
    _PDF_FONTS_READY = True

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------- #
# 双语标签（zh / en；bilingual 模式取「中文 / English」）
# ---------------------------------------------------------------------- #

LABELS: Dict[str, Tuple[str, str]] = {
    "report":           ("报告", "Report"),
    "gen_time":         ("报告生成时间", "Report generation time"),
    "cov_time":         ("报告涵盖时间", "Report coverage time"),
    "data_source":      ("数据源", "Data sources"),
    "overview":         ("一、报告速览", "I. Report Overview"),
    "display":          ("二、分类论文展示", "II. Classified Paper Display"),
    "trends":           ("三、研究趋势", "III. Research Trends"),
    "hotspot":          ("热点", "Hotspot"),
    "intro":            ("热点主题介绍", "Hotspot intro"),
    "in_category":      ("本方向共收录", "Papers in this direction"),
    "authors":          ("作者", "Authors"),
    "et_al":            ("等", "et al."),
    "pub_time":         ("发表时间", "Published"),
    "venue":            ("发表期刊", "Venue"),
    "citations":        ("引用量", "Citations"),
    "doi":              ("DOI", "DOI"),
    "link":             ("链接", "Link"),
    "abstract":         ("Abstract", "Abstract"),
    "problem":          ("解决的问题", "Problem"),
    "existing":         ("现有方案", "Existing approaches"),
    "new_approach":     ("新方案", "New approach"),
    "results":          ("效果及局限性", "Results & limitations"),
    "not_mentioned":    ("未明确提及", "Not explicitly mentioned"),
    "value_app":        ("研究价值与应用", "Value & applications"),
    "apa":              ("APA 引用", "APA Citation"),
    "overall":          ("整体分析", "Overall Analysis"),
    "foundational":     ("奠基性参考论文", "Foundational References"),
    "future_trends":    ("未来研究趋势", "Future Trends"),
    "gaps":             ("可深挖方向", "Directions Worth Exploring"),
    "no_papers":        ("本分类暂无论文", "No papers in this category"),
    "footer_by":        ("由 Academic Report 自动生成",
                         "Generated by Academic Report"),
}


def _label(key: str, lang: str) -> str:
    """取标签；bilingual 时返回「中文 / English」。"""
    zh, en = LABELS.get(key, (key, key))
    if lang == "en":
        return en
    if lang == "zh":
        return zh
    return f"{zh} / {en}"


class ReportGenerator:
    """学术报告生成器（MD/PDF）"""

    def __init__(self, paper_filter=None, paper_analyzer=None):
        """
        Args:
            paper_filter:    热点聚类 + 介绍（默认 PaperFilter()）
            paper_analyzer:  信息提取 + 整体分析 + 奠基论文（默认 PaperAnalyzer()）
        """
        # 延迟导入，避免循环依赖；允许测试注入假对象
        from paper_filter import PaperFilter
        from paper_analyzer import PaperAnalyzer

        self.skill_dir = Path(__file__).parent.parent
        self.paper_filter = paper_filter or PaperFilter()
        self.paper_analyzer = paper_analyzer or PaperAnalyzer()

    # ----------------------------- 公共入口 ---------------------------- #

    def generate_report(self, papers: List[Paper], intent: SearchIntent,
                        output_format: str = "markdown") -> Union[str, bytes]:
        """
        生成学术报告。

        Args:
            papers: 论文列表（建议先经 paper_filter 筛选排序）
            intent: 搜索意图（提供 research_field / language / 时间范围）
            output_format: 'markdown'（返回 str）或 'pdf'（返回 bytes）

        Returns:
            markdown 模式返回 MD 字符串；pdf 模式返回 PDF 二进制（bytes）。
        """
        lang = (intent.language or "bilingual").lower()
        if lang not in ("zh", "en", "bilingual"):
            lang = "bilingual"

        logger.info("生成 %s 报告（%s），含 %d 篇论文",
                    output_format, lang, len(papers))

        ctx = self._prepare(papers, intent, lang)
        md = self._render_markdown(ctx, intent, lang)

        if output_format == "markdown":
            report: Union[str, bytes] = md
        elif output_format == "pdf":
            report = self._convert_to_pdf(md, intent, lang)
        else:
            raise ValueError(f"不支持的格式: {output_format}")

        logger.info("报告生成完成")
        return report

    def generate_both(self, papers: List[Paper], intent: SearchIntent,
                      lang: Optional[str] = None) -> tuple:
        """
        一次生成 Markdown + PDF，共享同一次 _prepare（避免重复跑 LLM 四要素 /
        研究方向 / 奠基论文查找）。供 pipeline 每次运行同时产出两份报告时调用。

        Returns:
            (markdown_text, pdf_bytes|None, ctx) —— PDF 生成失败时 pdf_bytes 为 None
            （仅回退输出 MD，不抛异常）；ctx 含 papers/classified/trends 等，供调用方
            写运行日志 run_data.json，无需重算。
        """
        lang = (lang or intent.language or "bilingual").lower()
        if lang not in ("zh", "en", "bilingual"):
            lang = "bilingual"
        logger.info("生成 MD+PDF 报告（%s），含 %d 篇论文", lang, len(papers))
        ctx = self._prepare(papers, intent, lang)
        md = self._render_markdown(ctx, intent, lang)
        try:
            pdf = self._convert_to_pdf(md, intent, lang)
        except Exception as e:
            logger.error("PDF 生成失败，回退仅输出 Markdown: %s", e)
            pdf = None
        logger.info("报告生成完成（MD %d 字符%s）",
                    len(md),
                    f" / PDF {len(pdf)} 字节" if pdf else " / PDF 失败")
        return md, pdf, ctx

    def save_report(self, report: str, output_path: str) -> Path:
        """保存 Markdown 报告到文件，返回文件路径"""
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(report, encoding="utf-8")
        logger.info("报告已保存: %s", out)
        return out

    def save_pdf(self, pdf_bytes: bytes, output_path: str) -> Path:
        """保存 PDF 二进制报告到文件，返回文件路径"""
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(pdf_bytes)
        logger.info("PDF 报告已保存: %s", out)
        return out

    # ----------------------------- 数据准备 ---------------------------- #

    def _prepare(self, papers: List[Paper], intent: SearchIntent,
                 lang: str) -> Dict:
        """填充分析字段 + 热点聚类 + 各热点介绍/整体分析/奠基论文"""
        # 1. 单篇结构化提取（填充 research_content / innovations / conclusions）
        papers = self.paper_analyzer.analyze_papers(papers, lang)

        # 2. 热点聚类（传入查询+领域作为主题提示，提升热点相关性）
        topic_hint = f"{intent.query} {intent.research_field}"
        classified = self.paper_filter.classify_by_topic(papers, topic_hint)

        # 3. 每热点的介绍 / 整体分析 / 奠基性参考（Option B：委托）
        hotspot_intros: Dict[str, str] = {}
        overall_analyses: Dict[str, str] = {}
        foundational: Dict[str, List[str]] = {}
        for category, cat_papers in classified.items():
            hotspot_intros[category] = (
                self.paper_filter.generate_hotspot_intro(category, cat_papers)
            )
            overall_analyses[category] = (
                self.paper_analyzer.generate_overall_analysis(category, cat_papers)
            )
            foundational[category] = (
                self.paper_analyzer.find_foundational_papers(cat_papers, top_n=3)
            )

        # 4. 报告速览（逐篇，不遗漏）
        summary = self._generate_summary(papers, classified, lang)

        # 5. 研究趋势（基于本次论文派生）
        trends = self._analyze_trends(papers, lang)

        return {
            "papers": papers,
            "classified": classified,
            "hotspot_intros": hotspot_intros,
            "overall_analyses": overall_analyses,
            "foundational": foundational,
            "summary": summary,
            "trends": trends,
        }

    # ----------------------------- 速览 -------------------------------- #

    def _generate_summary(self, papers: List[Paper],
                          classified: Dict[str, List[Paper]],
                          lang: str) -> str:
        """
        报告速览（报告格式设计.md §4）：**按热点分组、逐篇概述**——
        列出每个热点，并在每个热点下概括其中**每一篇**论文的核心内容，
        让用户一眼看到报告覆盖的全部论文及其要点。
        """
        total = len(papers)
        n_hotspots = len(classified)
        highly_cited = sum(1 for p in papers if p.citation_count >= 100)

        # 开篇（bilingual 给中英两行）
        zh_open = (f"本报告收录 {total} 篇论文，分为 {n_hotspots} 个研究热点"
                   f"（其中高被引 {highly_cited} 篇）。以下按热点逐篇概述其核心内容：")
        en_open = (f"This report includes {total} papers across {n_hotspots} "
                   f"research hotspots ({highly_cited} highly cited). "
                   f"Each hotspot and its papers are summarized below:")
        head = {"zh": zh_open, "en": en_open,
                "bilingual": f"{zh_open}\n{en_open}"}[lang]

        lines = [head, ""]
        # 按热点分组：热点名 + 篇数，其下逐篇给「标题：核心内容」
        for category, cat_papers in classified.items():
            n = len(cat_papers)
            if lang == "en":
                lines.append(f"- {category} ({n} papers):")
            elif lang == "zh":
                lines.append(f"- 热点「{category}」({n} 篇)：")
            else:  # bilingual
                lines.append(f"- 「{category}」({n} 篇 / {n} papers):")
            for p in cat_papers:
                finding = self._paper_finding(p)
                title = (p.title or "").strip()
                if lang == "en":
                    lines.append(f"  - {title}: {finding}")
                elif lang == "zh":
                    lines.append(f"  - 《{title}》：{finding}")
                else:  # bilingual
                    lines.append(f"  - 《{title}》: {finding}")
        return "\n".join(lines)

    @staticmethod
    def _paper_finding(paper: Paper) -> str:
        """
        单篇核心内容概要（速览用）：取完整摘要前 1-2 句（问题+方法），
        回退标题。控制在约 160 字符内，不出现省略号。
        """
        text = (paper.condensed_abstract or paper.abstract or ""
                ).replace("\n", " ").strip()
        if not text:
            return (paper.title or "").strip()
        first = text.find(". ")
        if 0 < first < 200:
            second = text.find(". ", first + 2)
            if 0 < second < 320:
                return text[:second + 1].strip()
            return text[:first + 1].strip()
        return text[:160].rstrip()

    # ----------------------------- 研究趋势 ---------------------------- #

    def _analyze_trends(self, papers: List[Paper],
                        lang: str) -> Dict[str, List[str]]:
        """
        研究趋势 + 研究缺口，均从本次收录论文派生（避免空泛套话，§6）。
        bilingual 时给出中英双语条目。
        """
        from collections import Counter

        kw: Counter = Counter()
        venues: List[str] = []
        citations: List[int] = []
        years: List[int] = []
        blob = []
        for p in papers:
            kw.update(p.keywords)
            venues.append((p.venue or "").lower())
            citations.append(p.citation_count)
            years.append(p.year or 0)
            blob.append(f"{p.title} {p.abstract}".lower())
        text = " ".join(blob)

        # —— 主要趋势：高频关键词（基于论文）——
        main_pairs: List[Tuple[str, str]] = []
        for keyword, freq in kw.most_common(5):
            if freq >= 1:
                main_pairs.append((
                    f"{keyword}（{freq} 篇）相关研究活跃",
                    f"{keyword} ({freq} papers) is an active trend",
                ))
        if not main_pairs:
            main_pairs.append((
                "本批论文覆盖多个相关方向，整体研究活跃",
                "These papers span several related directions with active research",
            ))

        # —— 研究方向（深挖方向，**非论文缺陷评价**）：基于本批论文内容，
        #    为读者推断 1-2 个可继续推进的方向。LLM 主路径 → 规则回退。 ——
        from llm_analyzer import generate_research_directions   # 延迟导入，避免循环依赖
        gap_pairs: List[Tuple[str, str]] = generate_research_directions(papers, lang)

        def render(pairs: List[Tuple[str, str]]) -> List[str]:
            if lang == "en":
                return [en for _, en in pairs]
            if lang == "zh":
                return [zh for zh, _ in pairs]
            return [f"{zh} / {en}" for zh, en in pairs]

        return {"main_trends": render(main_pairs),
                "research_gaps": render(gap_pairs)}

    # ----------------------------- Markdown 渲染 ----------------------- #

    def _render_markdown(self, ctx: Dict, intent: SearchIntent,
                         lang: str) -> str:
        """渲染四段式 Markdown 报告"""
        research_field = intent.research_field or intent.query or "学术研究"
        time_range = self._format_time_range(intent)
        coverage_time = self._format_coverage_time(intent)
        report_time = datetime.now().strftime("%Y-%m-%d %H:%M")

        lines: List[str] = []

        # —— 标题 + 时间 ——
        lines.append(self._render_title(research_field, time_range, lang))
        lines.append("")
        lines.append(f"*{_label('gen_time', lang)}: {report_time}*")
        lines.append(f"*{_label('cov_time', lang)}: {coverage_time}*")
        lines.append(f"*{_label('data_source', lang)}: arXiv, Semantic Scholar, OpenAlex*")
        lines.append("")
        lines.append("---")
        lines.append("")

        # —— 一、报告速览 ——
        lines.append(f"## {_label('overview', lang)}")
        lines.append("")
        lines.append(ctx["summary"])
        lines.append("")
        lines.append("---")
        lines.append("")

        # —— 二、分类论文展示 ——
        lines.append(f"## {_label('display', lang)}")
        lines.append("")

        for idx, (category, cat_papers) in enumerate(
                ctx["classified"].items(), 1):
            lines.append(self._render_hotspot_heading(idx, category, lang))
            lines.append("")
            lines.append(f"**{_label('intro', lang)}**："
                         f"{ctx['hotspot_intros'][category]}")
            lines.append("")

            if not cat_papers:
                lines.append(_label("no_papers", lang))
                lines.append("")
                lines.append("---")
                lines.append("")
                continue

            lines.append(f"{_label('in_category', lang)} "
                         f"{len(cat_papers)} 篇。")
            lines.append("")

            for p_idx, paper in enumerate(cat_papers, 1):
                lines.extend(self._render_paper(p_idx, paper, lang))
                lines.append("---")
                lines.append("")

            # 整体分析
            lines.append(f"**{_label('overall', lang)}**: "
                         f"{ctx['overall_analyses'][category]}")
            lines.append("")

            # 奠基性参考论文
            refs = ctx["foundational"].get(category, [])
            if refs:
                lines.append(f"**{_label('foundational', lang)}**:")
                for ref in refs[:3]:
                    lines.append(f"- {ref}")
                lines.append("")

            lines.append("---")
            lines.append("")

        # —— 三、研究趋势 ——
        lines.append(f"## {_label('trends', lang)}")
        lines.append("")
        lines.append(f"### {_label('future_trends', lang)}")
        lines.append("")
        for t in ctx["trends"]["main_trends"]:
            lines.append(f"- {t}")
        lines.append("")
        lines.append(f"### {_label('gaps', lang)}")
        lines.append("")
        for g in ctx["trends"]["research_gaps"]:
            lines.append(f"- {g}")
        lines.append("")

        # —— 报告尾部 ——
        lines.append("---")
        lines.append("")
        lines.append(f"**{_label('gen_time', lang)}**: {report_time}")
        lines.append(f"**{_label('footer_by', lang)}**")
        lines.append("")

        return "\n".join(lines)

    # ----------------------------- 子渲染 ------------------------------ #

    def _render_title(self, field: str, time_range: str, lang: str) -> str:
        """标题：bilingual 双语两行（§7）"""
        prefix = f"{time_range} " if time_range else ""
        zh = f"# {prefix}{field} 报告"
        en = f"# {prefix}{field} Report"
        if lang == "en":
            return en
        if lang == "zh":
            return zh
        return f"{zh}\n{en}"

    def _render_hotspot_heading(self, idx: int, category: str,
                                lang: str) -> str:
        """热点标题：热点一 / Hotspot 1"""
        if lang == "en":
            return f"### Hotspot {idx}: {category}"
        if lang == "zh":
            return f"### 热点{self._numeral(idx)}：{category}"
        return (f"### 热点{self._numeral(idx)}：{category} / "
                f"Hotspot {idx}: {category}")

    def _render_paper(self, idx: int, paper: Paper, lang: str) -> List[str]:
        """单篇论文块：基本信息 + 四要素摘录（从摘要抽取）+ APA"""
        et_al = f"{_label('et_al', lang)}" if len(paper.authors) > 3 else ""
        authors_str = ", ".join(paper.authors[:3]) + (f" {et_al}" if et_al else "")
        out: List[str] = [f"#### {idx}. {paper.title}", ""]

        # 基本信息（发表时间独立字段，§5.2）
        out.append(f"- **{_label('authors', lang)}**: {authors_str}")
        out.append(f"- **{_label('pub_time', lang)}**: {paper.year}")
        out.append(f"- **{_label('venue', lang)}**: {paper.venue}")
        out.append(f"- **{_label('citations', lang)}**: {paper.citation_count}")
        if paper.doi:
            out.append(f"- **{_label('doi', lang)}**: {paper.doi}")
        if paper.url:
            out.append(f"- **{_label('link', lang)}**: {paper.url}")
        out.append("")

        # 四要素（§5.2）：闭源标注 / 四段 / 全空回退 Abstract
        if getattr(paper, "analysis_source", "") == "unavailable":
            # 闭源/无开放摘要与全文：不展示空四要素，改标注 + 检索链接
            url = (f"https://doi.org/{paper.doi}" if paper.doi
                   else f"https://scholar.google.com/scholar?q={paper.title}")
            out.append(f"**⚠️ 无法自动分析 / Unavailable for auto-analysis**:")
            out.append(f"本文为闭源/无开放摘要与全文，四要素无法自动分析，"
                       f"请自行检索原文：{url}")
            out.append("")
        else:
            parts = [
                ("problem", paper.problem),
                ("existing", paper.existing_approaches),
                ("new_approach", paper.new_approach),
                ("results", paper.results_limitations),
            ]
            if any(val for _, val in parts):
                for key, val in parts:
                    out.append(f"**{_label(key, lang)}**:")
                    out.append(val if val else _label("not_mentioned", lang))
                    out.append("")
            else:
                out.append(f"**{_label('abstract', lang)}**:")
                abstract = (paper.condensed_abstract
                            or (paper.abstract or "").replace("\n", " ").strip())
                if not abstract:
                    abstract = "（暂无摘要 / No abstract available）"
                out.append(abstract)
                out.append("")

        # 研究价值与应用场景（analyzer 推断；非空才输出，闭源论文跳过）
        if (getattr(paper, "analysis_source", "") != "unavailable"
                and getattr(paper, "value_application", "")):
            out.append(f"**{_label('value_app', lang)}**:")
            out.append(paper.value_application)
            out.append("")

        # APA 引用
        out.append(f"**{_label('apa', lang)}**:")
        out.append(f"> {format_apa_citation(paper)}")
        out.append("")
        return out

    # ----------------------------- PDF 生成 ---------------------------- #

    # 配色沿用原 HTML 模板（视觉连续）
    _C_PRIMARY = "#3498db"   # 主色：标题下划线 / 左蓝条 / 引用左条
    _C_H1 = "#2c3e50"        # H1 深石板蓝
    _C_H2 = "#34495e"        # H2 石板蓝
    _C_TEXT = "#333333"      # 正文
    _C_META = "#7f8c8d"      # 元信息 / 页眉页脚 灰
    _C_QUOTE = "#555555"     # 引用灰
    _C_BG_QUOTE = "#f8f9fa"  # 引用浅底
    _C_HR = "#ecf0f1"        # 细分隔线

    def _pdf_styles(self) -> Dict[str, "ParagraphStyle"]:
        """构建 PDF 段落样式集（全部 wordWrap=CJK，否则长中文行溢出右边距）"""
        common = dict(fontName=PDF_FONT_NAME, wordWrap="CJK")
        return {
            "h1": ParagraphStyle("h1", **common, fontSize=20, leading=26,
                                 textColor=colors.HexColor(self._C_H1),
                                 spaceBefore=4, spaceAfter=4),
            "h2": ParagraphStyle("h2", **common, fontSize=16, leading=22,
                                 textColor=colors.HexColor(self._C_H2),
                                 spaceBefore=14, spaceAfter=8),
            "h3": ParagraphStyle("h3", **common, fontSize=13, leading=18,
                                 textColor=colors.HexColor(self._C_H1),
                                 spaceBefore=10, spaceAfter=5),
            "h4": ParagraphStyle("h4", **common, fontSize=11.5, leading=16,
                                 textColor=colors.HexColor(self._C_H2),
                                 spaceBefore=9, spaceAfter=3),
            "body": ParagraphStyle("body", **common, fontSize=10.5, leading=16,
                                   textColor=colors.HexColor(self._C_TEXT),
                                   spaceAfter=5),
            "meta": ParagraphStyle("meta", **common, fontSize=9, leading=13,
                                   textColor=colors.HexColor(self._C_META),
                                   spaceAfter=2),
            "quote": ParagraphStyle("quote", **common, fontSize=9.5, leading=15,
                                    textColor=colors.HexColor(self._C_QUOTE)),
            "bullet": ParagraphStyle("bullet", **common, fontSize=10.5,
                                     leading=16,
                                     textColor=colors.HexColor(self._C_TEXT),
                                     leftIndent=16, bulletIndent=3,
                                     spaceAfter=2),
            "bullet2": ParagraphStyle("bullet2", **common, fontSize=10.5,
                                      leading=16,
                                      textColor=colors.HexColor(self._C_TEXT),
                                      leftIndent=32, bulletIndent=19,
                                      spaceAfter=2),
        }

    @staticmethod
    def _format_inline_md(text: str) -> str:
        """
        行内 Markdown → reportlab Paragraph mini-markup：先转义 &<>，再
        **bold** → <b>、*italic* → <i>、`code` → <font face=Courier>（粗体先于
        斜体，确保 ** 被先消耗）。
        """
        if not text:
            return ""
        out = (text.replace("&", "&amp;").replace("<", "&lt;")
               .replace(">", "&gt;"))
        out = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", out)
        out = re.sub(r"(?<!\*)\*([^*\n]+?)\*(?!\*)", r"<i>\1</i>", out)
        out = re.sub(r"`([^`]+?)`", r'<font face="Courier">\1</font>', out)
        return out

    def _barred(self, flowable, content_width: float,
                bg: Optional[str] = None) -> "Table":
        """给 flowable 加左侧蓝条（+ 可选浅底），模拟 HTML 的 border-left。"""
        tbl = Table([[flowable]], colWidths=[content_width])
        style = [
            ("LINEBEFORE", (0, 0), (0, -1), 3,
             colors.HexColor(self._C_PRIMARY)),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]
        if bg:
            style.append(("BACKGROUND", (0, 0), (-1, -1),
                          colors.HexColor(bg)))
        tbl.setStyle(TableStyle(style))
        return tbl

    def _on_page(self, title: str):
        """页眉（报告标题，首页略避免与正文 H1 重复）/ 页脚（页码）回调"""
        def _draw(canvas, doc):
            canvas.saveState()
            canvas.setFont(PDF_FONT_NAME, 9)
            canvas.setFillColor(colors.HexColor(self._C_META))
            canvas.drawRightString(
                A4[0] - 2 * cm, 1.2 * cm,
                f"第 {doc.page} 页 / Page {doc.page}")
            if doc.page > 1:
                canvas.setFont(PDF_FONT_NAME, 8)
                canvas.drawString(2 * cm, A4[1] - 1.2 * cm, title)
            canvas.restoreState()
        return _draw

    def _convert_to_pdf(self, md_text: str, intent: SearchIntent,
                        lang: str) -> bytes:
        """
        Markdown → PDF（reportlab Platypus）。行向解析 _render_markdown 产出的
        固定 MD 子集（标题 / `-` 列表 / `>` 引用 / `---` / 行内粗斜体），渲染为
        学术风格 PDF。正文自然跨页；各标题前用 CondPageBreak 避免标题孤悬页底
        （不做整块 KeepTogether——否则标题后易出现大片空白）。依赖 reportlab；
        未安装时抛 RuntimeError（由 generate_both 捕获回退）。
        """
        if not _HAS_REPORTLAB:
            raise RuntimeError("reportlab 未安装，无法生成 PDF")
        _ensure_pdf_fonts()

        title_field = intent.research_field or intent.query or "学术研究"
        time_range = self._format_time_range(intent)
        prefix = f"{time_range} " if time_range else ""
        title = f"{prefix}{title_field} 报告 / Report"

        left = right = top = bottom = 2 * cm
        content_width = A4[0] - left - right
        styles = self._pdf_styles()
        primary = colors.HexColor(self._C_PRIMARY)

        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=left, rightMargin=right,
            topMargin=top, bottomMargin=bottom,
            title=title, author="Academic Report")
        story: List = []

        # ---- 行向 walker ----
        lines = md_text.split("\n")
        n = len(lines)
        i = 0

        para_buf: List[str] = []
        quote_buf: List[str] = []
        list_items: List[Tuple[int, str]] = []

        def flush_para():
            nonlocal para_buf
            if para_buf:
                story.append(Paragraph(self._format_inline_md(" ".join(para_buf)),
                                       styles["body"]))
                para_buf = []

        def flush_quote():
            nonlocal quote_buf
            if quote_buf:
                text = " ".join(self._format_inline_md(ln) for ln in quote_buf)
                story.append(self._barred(Paragraph(text, styles["quote"]),
                                          content_width, bg=self._C_BG_QUOTE))
                quote_buf = []

        def flush_list():
            nonlocal list_items
            for depth, text in list_items:
                st = styles["bullet2"] if depth >= 1 else styles["bullet"]
                story.append(Paragraph(self._format_inline_md(text), st,
                                       bulletText="•"))
            list_items = []

        def flush_all():
            flush_list(); flush_quote(); flush_para()

        while i < n:
            stripped = lines[i].strip()

            # 水平分隔线
            if re.match(r"^-{3,}\s*$", stripped):
                flush_all()
                story.append(HRFlowable(width="100%", thickness=0.5,
                                        color=colors.HexColor(self._C_HR),
                                        spaceBefore=8, spaceAfter=8))
                i += 1
                continue

            m4 = re.match(r"^####\s+(.*)$", stripped)
            m3 = re.match(r"^###\s+(.*)$", stripped)
            m2 = re.match(r"^##\s+(.*)$", stripped)
            m1 = re.match(r"^#\s+(.*)$", stripped)

            if m4:                       # 单篇论文标题
                flush_all()
                story.append(CondPageBreak(2.5 * cm))   # 避免标题孤悬页底
                story.append(Paragraph(self._format_inline_md(m4.group(1)),
                                       styles["h4"]))
            elif m3:                     # 热点 / 子小节标题
                flush_all()
                story.append(CondPageBreak(3.5 * cm))   # 标题+引言同页，避免标题后大片空白
                story.append(Paragraph(self._format_inline_md(m3.group(1)),
                                       styles["h3"]))
            elif m2:                     # 一级章节标题
                flush_all()
                story.append(CondPageBreak(4 * cm))
                story.append(self._barred(
                    Paragraph(self._format_inline_md(m2.group(1)),
                              styles["h2"]), content_width))
            elif m1:                     # 报告标题（双语：两行连续 H1 合并）
                flush_all()
                j = i + 1
                if j < n and re.match(r"^#\s+", lines[j].strip()):
                    second = re.match(r"^#\s+(.*)$",
                                      lines[j].strip()).group(1)
                    merged = (self._format_inline_md(m1.group(1)) + "<br/>"
                              + self._format_inline_md(second))
                    story.append(Paragraph(merged, styles["h1"]))
                    i = j  # 跳过第二行（循环末尾再 +1）
                else:
                    story.append(Paragraph(
                        self._format_inline_md(m1.group(1)), styles["h1"]))
                story.append(HRFlowable(width="100%", thickness=2,
                                        color=primary,
                                        spaceBefore=2, spaceAfter=12))
            elif stripped == "":
                flush_all()
            elif stripped.startswith(">"):
                flush_list(); flush_para()
                quote_buf.append(stripped.lstrip("> ").rstrip())
            else:
                mb = re.match(r"^(\s*)[-*]\s+(.*)$", lines[i])
                if mb:
                    flush_quote(); flush_para()
                    depth = 1 if len(mb.group(1)) >= 2 else 0
                    list_items.append((depth, mb.group(2)))
                else:
                    flush_list(); flush_quote()
                    para_buf.append(stripped)
            i += 1

        flush_all()

        doc.build(story, onFirstPage=self._on_page(title),
                  onLaterPages=self._on_page(title))
        return buf.getvalue()

    # ----------------------------- 工具 -------------------------------- #

    def _format_time_range(self, intent: SearchIntent) -> str:
        """标题中的时间范围，如 '2023-2025'"""
        start = intent.start_date.year if intent.start_date else None
        end = intent.end_date.year if intent.end_date else None
        if start and end:
            return f"{start}-{end}"
        if start:
            return f"{start}-至今"
        if end:
            return f"截至{end}"
        return ""

    def _format_coverage_time(self, intent: SearchIntent) -> str:
        """报告涵盖时间（论文发表区间，月粒度）"""
        if not intent.start_date and not intent.end_date:
            return "不限 / N/A"
        start = (intent.start_date.strftime("%Y-%m")
                 if intent.start_date else "起始不限")
        end = intent.end_date.strftime("%Y-%m") if intent.end_date else "至今"
        return f"{start} 至 {end}"

    @staticmethod
    def _numeral(n: int) -> str:
        """阿拉伯 → 中文数字（1→一 … 10→十，≥20 用阿拉伯）"""
        numerals = "零一二三四五六七八九十"
        if n <= 10:
            return numerals[n]
        if n < 20:
            return f"十{numerals[n - 10]}"
        return str(n)


# ---------------------------------------------------------------------- #
# 命令行入口
# ---------------------------------------------------------------------- #

def main() -> None:
    """命令行：从 JSON 读取论文 + 意图，生成报告"""
    import argparse
    import json

    parser = argparse.ArgumentParser(description="生成学术报告")
    parser.add_argument("--input", required=True, help="论文 JSON 文件")
    parser.add_argument("--output", required=True, help="输出报告路径")
    parser.add_argument("--format", default="markdown",
                        choices=["markdown", "pdf"])
    parser.add_argument("--intent", help="搜索意图 JSON 文件")
    args = parser.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        papers = [Paper.from_dict(p) for p in json.load(f)]

    intent = SearchIntent(query="report", keywords=[], research_field="学术研究",
                          language="bilingual", max_results=50)
    if args.intent:
        with open(args.intent, "r", encoding="utf-8") as f:
            data = json.load(f)
        for k, v in data.items():
            if hasattr(intent, k):
                setattr(intent, k, v)

    gen = ReportGenerator()
    report = gen.generate_report(papers, intent, args.format)
    if isinstance(report, (bytes, bytearray)):
        gen.save_pdf(bytes(report), args.output)
    else:
        gen.save_report(report, args.output)
    print(f"报告已生成: {args.output}")


if __name__ == "__main__":
    main()
